# Generated by Django 5.2.7 on 2025-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="study_count",
            field=models.IntegerField(default=0),
        ),
    ]
