# Generated by Django 5.2.7 on 2025-12-06 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0004_topic_study_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="question",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
